name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:3.15@sha256:69463fdff1f025c908939e86d4714b4d5518776954ca627cbeff4c74bcea5b22
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: apk add --no-cache bash shfmt shellcheck
      - name: test
        run: ./test
